version: '3.4'

services:
  citiesapp:
    image: ${DOCKER_REGISTRY-}citiesapp
    build:
      context: .
      dockerfile: src/CitiesApp/Dockerfile
    depends_on:
      - postgres
  postgres:
    image: postgis/postgis:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=db_dev_weatherapp
    volumes:
      - ./dev/postgres:/var/lib/postgresql/data
