# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  

jobs:

  build:
    runs-on: ubuntu-latest
    
    services:
      image: docker:24.0-dind
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set permissions on docker socket
      run: ls -l /var/run/docker.sock
      
#     - name: Run Integration Tests
#       run: go run pipeline.go

